// Qs1. Create a program that generates a random number representing a dice roll.
//      [The number should be between 1 and 6].
let random = Math.floor(Math.random() * 6) + 1;
console.log("The number generated by rolling a dice is: ",random);
// Qs2. Create an object representing a car that stores the following properties for the car, name, model, color.
//      Print the car's name.
const car = {
    name: "BMW",
    model: 2,
    color: "White"
}
console.log("Car's name is: ",car.name);
// Qs3. Create an object Person with their name, age and city.
//      Edit their city's original value to change it to "New York".
//      Add a new property country and set it to the United States.
let person = {
    name: "Bhushan",
    age: 22,
    city: "Delhi"
}
console.log("Details of person are: ", person);
person.city = "New York";
console.log("Updated the city: ", person);
person.country = "United States";
console.log("Updated with country: ",person);